/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/home/index" |
  "/pages/learn/index" |
  "/pages/mall/index" |
  "/pages/mine/index" |
  "/pages/orders/index" |
  "/pagesOrder/chat/index" |
  "/pagesOrder/detail/index" |
  "/pagesOrder/publish/index" |
  "/pagesOrder/select-pilot/index" |
  "/pagesLearn/caac-detail/index" |
  "/pagesLearn/course-detail/index" |
  "/pagesLearn/enroll/index" |
  "/pagesLearn/subsidy/index" |
  "/pagesRepair/apply/index" |
  "/pagesRepair/order/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/orders/index" | "/pages/learn/index" | "/pages/mall/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
